create sequence seq_t_bank_mapping;
create table t_bank_mapping(
id number(4) primary key,
interface_no varchar2(20) not null unique,    -- 交易码
remarks varchar2(500) ,											  -- 备注
writer  VARCHAR2(50),												  -- 创建人
create_date date DEFAULT sysdate , 						-- 创建时间
modify_time date default sysdate,							-- 修改时时间
send varchar2(4000) not null,						  --发送报文
receive VARCHAR2(4000) not null          -- 接收报文
);


Insert into T_BANK_MAPPING (ID,INTERFACE_NO,REMARKS,WRITER,CREATE_DATE,MODIFY_TIME,SEND,RECEIVE) values (27,'1025','备注啊','测试人员',to_date('13-7月 -18','DD-MON-RR'),to_date('13-7月 -18','DD-MON-RR'),'services,这个是交易号,1,,
SYS_HEAD,系统头部,1,,
SvcCd,服务代码,0,,
SvcScn,服务场景,0,,
CnsmSysId,调用方系统Id,0,,
CnsmSysSeqNo,调用方系统流水号,0,,
TranRetSt,交易返回状态,0,,
RetInf,交易返回信息数组,1,,
RetCd,返回码,0,,
RetMsg,交易返回信息,0,,
RetInf,交易返回信息数组,-1,,
SrcSysSeqNo,源发起系统流水号,0,,
SrcSysId,源发起系统Id,0,,
SYS_HEAD,系统头部,-1,,
APP_HEAD,app头部,1,,
BranchId,编号,0,,
TlrNo,代码,0,,
TlrPswd,密码,0,,
TlrLvl,标题,0,,
TlrTp,标题,0,,
BsnSeqNo,编号,0,,
APP_HEAD,app头部,-1,,
BODY,交易码,1,,
CstIdTp,客户标识类型,0,CstIdTpYiHui,默认值CstIdT
CstId,客户标识,0,CstIdYiHui,默认值CstId
LoctStr,定位串,0,LoctStrYiHui,默认值LoctStr
QryLnNum,查询行数,0,QryLnNumYiHui,默认值QryLnNum
BODY,交易码,-1,,
services,这个是交易号,-1,,
','services,这个是交易号,1,,
SYS_HEAD,系统头部,1,,
SvcCd,服务代码,0,,
SvcScn,服务场景,0,,
CnsmSysId,调用方系统Id,0,,
CnsmSysSeqNo,调用方系统流水号,0,,
TranRetSt,交易返回状态,0,,
RetInf,交易返回信息数组,1,,
RetCd,返回码,0,,
RetMsg,交易返回信息,0,,
RetInf,交易返回信息数组,-1,,
SrcSysSeqNo,交易返源发起系统流水号回信息,0,,
SrcSysId,源发起系统Id,0,,
SYS_HEAD,系统头部,-1,,
APP_HEAD,app头部,1,,
APP_HEAD,app头部,-1,,
BODY,body部分,1,,
VerNo,版本号,0,VerNoYiHui,默认值VerNo
VrfyNo,未知编号,0,VrfyNoYiHuiHui,默认值VrfyNo
TranCd,前置交易码,0,TranCdYiHui,默认值VrfyNo
RqsTm,未知编号,0,RqsTmYiHui,RqsTm默认值
TotRcrdNum,总记录数,0,TotRcrdNumYiHui,默认值
TotPgNo,总页数,0,TotPgNoYiHui,默认值
PgRcrdNo,每页记录数,0,PgRcrdNoYiHui,默认值PgRcrdNoYiHui
GdsMssgArray,商品信息数组,1,GdsMssgArrayYiHui,默认值
CmdtyCd,商品编号,0,CmdtyCdYiHuiYiHui,默认值
CmdtyNm,商品名称,0,CmdtyNmYiHuiYiHui,默认值
CmdtyDsc,商品描述,0,CmdtyDscYiHui,默认值
CmdtyPntsPrc,商品描述,0,CmdtyPntsPrcYiHui,默认值CmdtyPntsPrc
CmdtyCashPrc,商品所需现金,0,CmdtyCashPrcYiHui,默认值CmdtyCashPrc
GdsTm,商品描述,0,GdsTmYiHui,默认值GdsTm
CmdtyLvlScr,商品评分,0,CmdtyLvlScrYiHui,默认值CmdtyLvlScrYiHui
PhotoNo,商品评分,0,PhotoNoYiHui,默认值PhotoNoYiHui
CnsmRuleID,商品评分,0,CnsmRuleIDYiHui,默认值CnsmRuleIDYiHui
CnsmRuleDsc,商品评分,0,CnsmRuleDscYiHui,默认值CnsmRuleDsc
GdsMssgArray,商品信息数组,-1,GdsMssgArrayYiHui,默认值GdsMssgArray
BODY,body结束,-1,GdsMssgArrayYiHui,默认值BODY
services,这个是交易号,1,,
');
Insert into T_BANK_MAPPING (ID,INTERFACE_NO,REMARKS,WRITER,CREATE_DATE,MODIFY_TIME,SEND,RECEIVE) values (26,'1024','备注啊','测试人员',to_date('13-7月 -18','DD-MON-RR'),to_date('13-7月 -18','DD-MON-RR'),'services,这个是交易号,1,,
SYS_HEAD,系统头部,1,,
SvcCd,服务代码,0,,
SvcScn,服务场景,0,,
CnsmSysId,调用方系统Id,0,,
CnsmSysSeqNo,调用方系统流水号,0,,
TranRetSt,交易返回状态,0,,
RetInf,交易返回信息数组,1,,
RetCd,返回码,0,,
RetMsg,交易返回信息,0,,
RetInf,交易返回信息数组,-1,,
SrcSysSeqNo,源发起系统流水号,0,,
SrcSysId,源发起系统Id,0,,
SYS_HEAD,系统头部,-1,,
APP_HEAD,app头部,1,,
BranchId,编号,0,,
TlrNo,代码,0,,
TlrPswd,密码,0,,
TlrLvl,标题,0,,
TlrTp,标题,0,,
BsnSeqNo,编号,0,,
APP_HEAD,app头部,-1,,
BODY,交易码,1,,
CstIdTp,客户标识类型,0,CstIdTpYiHui,默认值CstIdT
CstId,客户标识,0,CstIdYiHui,默认值CstId
LoctStr,定位串,0,LoctStrYiHui,默认值LoctStr
QryLnNum,查询行数,0,QryLnNumYiHui,默认值QryLnNum
BODY,交易码,-1,,
services,这个是交易号,-1,,
','services,这个是交易号,1,,
SYS_HEAD,系统头部,1,,
SvcCd,服务代码,0,,
SvcScn,服务场景,0,,
CnsmSysId,调用方系统Id,0,,
CnsmSysSeqNo,调用方系统流水号,0,,
TranRetSt,交易返回状态,0,,
RetInf,交易返回信息数组,1,,
RetCd,返回码,0,,
RetMsg,交易返回信息,0,,
RetInf,交易返回信息数组,-1,,
SrcSysSeqNo,交易返源发起系统流水号回信息,0,,
SrcSysId,源发起系统Id,0,,
SYS_HEAD,系统头部,-1,,
APP_HEAD,app头部,1,,
APP_HEAD,app头部,-1,,
BODY,body部分,1,,
VerNo,版本号,0,VerNoYiHui,默认值VerNo
VrfyNo,未知编号,0,VrfyNoYiHuiHui,默认值VrfyNo
TranCd,前置交易码,0,TranCdYiHui,默认值VrfyNo
RqsTm,未知编号,0,RqsTmYiHui,RqsTm默认值
TotRcrdNum,总记录数,0,TotRcrdNumYiHui,默认值
TotPgNo,总页数,0,TotPgNoYiHui,默认值
PgRcrdNo,每页记录数,0,PgRcrdNoYiHui,默认值PgRcrdNoYiHui
GdsMssgArray,商品信息数组,1,GdsMssgArrayYiHui,默认值
CmdtyCd,商品编号,0,CmdtyCdYiHuiYiHui,默认值
CmdtyNm,商品名称,0,CmdtyNmYiHuiYiHui,默认值
CmdtyDsc,商品描述,0,CmdtyDscYiHui,默认值
CmdtyPntsPrc,商品描述,0,CmdtyPntsPrcYiHui,默认值CmdtyPntsPrc
CmdtyCashPrc,商品所需现金,0,CmdtyCashPrcYiHui,默认值CmdtyCashPrc
GdsTm,商品描述,0,GdsTmYiHui,默认值GdsTm
CmdtyLvlScr,商品评分,0,CmdtyLvlScrYiHui,默认值CmdtyLvlScrYiHui
PhotoNo,商品评分,0,PhotoNoYiHui,默认值PhotoNoYiHui
CnsmRuleID,商品评分,0,CnsmRuleIDYiHui,默认值CnsmRuleIDYiHui
CnsmRuleDsc,商品评分,0,CnsmRuleDscYiHui,默认值CnsmRuleDsc
GdsMssgArray,商品信息数组,-1,GdsMssgArrayYiHui,默认值GdsMssgArray
BODY,body结束,-1,GdsMssgArrayYiHui,默认值BODY
services,这个是交易号,1,,
');
Insert into T_BANK_MAPPING (ID,INTERFACE_NO,REMARKS,WRITER,CREATE_DATE,MODIFY_TIME,SEND,RECEIVE) values (28,'1026','备注啊','测试人员',to_date('13-7月 -18','DD-MON-RR'),to_date('13-7月 -18','DD-MON-RR'),'services,这个是交易号,1,,
SYS_HEAD,系统头部,1,,
SvcCd,服务代码,0,,
SvcScn,服务场景,0,,
CnsmSysId,调用方系统Id,0,,
CnsmSysSeqNo,调用方系统流水号,0,,
TranRetSt,交易返回状态,0,,
RetInf,交易返回信息数组,1,,
RetCd,返回码,0,,
RetMsg,交易返回信息,0,,
RetInf,交易返回信息数组,-1,,
SrcSysSeqNo,源发起系统流水号,0,,
SrcSysId,源发起系统Id,0,,
SYS_HEAD,系统头部,-1,,
APP_HEAD,app头部,1,,
BranchId,编号,0,,
TlrNo,代码,0,,
TlrPswd,密码,0,,
TlrLvl,标题,0,,
TlrTp,标题,0,,
BsnSeqNo,编号,0,,
APP_HEAD,app头部,-1,,
BODY,交易码,1,,
CstIdTp,客户标识类型,0,CstIdTpYiHui,默认值CstIdT
CstId,客户标识,0,CstIdYiHui,默认值CstId
LoctStr,定位串,0,LoctStrYiHui,默认值LoctStr
QryLnNum,查询行数,0,QryLnNumYiHui,默认值QryLnNum
BODY,交易码,-1,,
services,这个是交易号,-1,,
','services,这个是交易号,1,,
SYS_HEAD,系统头部,1,,
SvcCd,服务代码,0,,
SvcScn,服务场景,0,,
CnsmSysId,调用方系统Id,0,,
CnsmSysSeqNo,调用方系统流水号,0,,
TranRetSt,交易返回状态,0,,
RetInf,交易返回信息数组,1,,
RetCd,返回码,0,,
RetMsg,交易返回信息,0,,
RetInf,交易返回信息数组,-1,,
SrcSysSeqNo,交易返源发起系统流水号回信息,0,,
SrcSysId,源发起系统Id,0,,
SYS_HEAD,系统头部,-1,,
APP_HEAD,app头部,1,,
APP_HEAD,app头部,-1,,
BODY,body部分,1,,
VerNo,版本号,0,VerNoYiHui,默认值VerNo
VrfyNo,未知编号,0,VrfyNoYiHuiHui,默认值VrfyNo
TranCd,前置交易码,0,TranCdYiHui,默认值VrfyNo
RqsTm,未知编号,0,RqsTmYiHui,RqsTm默认值
TotRcrdNum,总记录数,0,TotRcrdNumYiHui,默认值
TotPgNo,总页数,0,TotPgNoYiHui,默认值
PgRcrdNo,每页记录数,0,PgRcrdNoYiHui,默认值PgRcrdNoYiHui
GdsMssgArray,商品信息数组,1,GdsMssgArrayYiHui,默认值
CmdtyCd,商品编号,0,CmdtyCdYiHuiYiHui,默认值
CmdtyNm,商品名称,0,CmdtyNmYiHuiYiHui,默认值
CmdtyDsc,商品描述,0,CmdtyDscYiHui,默认值
CmdtyPntsPrc,商品描述,0,CmdtyPntsPrcYiHui,默认值CmdtyPntsPrc
CmdtyCashPrc,商品所需现金,0,CmdtyCashPrcYiHui,默认值CmdtyCashPrc
GdsTm,商品描述,0,GdsTmYiHui,默认值GdsTm
CmdtyLvlScr,商品评分,0,CmdtyLvlScrYiHui,默认值CmdtyLvlScrYiHui
PhotoNo,商品评分,0,PhotoNoYiHui,默认值PhotoNoYiHui
CnsmRuleID,商品评分,0,CnsmRuleIDYiHui,默认值CnsmRuleIDYiHui
CnsmRuleDsc,商品评分,0,CnsmRuleDscYiHui,默认值CnsmRuleDsc
GdsMssgArray,商品信息数组,-1,GdsMssgArrayYiHui,默认值GdsMssgArray
BODY,body结束,-1,GdsMssgArrayYiHui,默认值BODY
services,这个是交易号,1,,
');
Insert into T_BANK_MAPPING (ID,INTERFACE_NO,REMARKS,WRITER,CREATE_DATE,MODIFY_TIME,SEND,RECEIVE) values (29,'1027','备注啊','测试人员',to_date('13-7月 -18','DD-MON-RR'),to_date('13-7月 -18','DD-MON-RR'),'services,这个是交易号,1,,
SYS_HEAD,系统头部,1,,
SvcCd,服务代码,0,,
SvcScn,服务场景,0,,
CnsmSysId,调用方系统Id,0,,
CnsmSysSeqNo,调用方系统流水号,0,,
TranRetSt,交易返回状态,0,,
RetInf,交易返回信息数组,1,,
RetCd,返回码,0,,
RetMsg,交易返回信息,0,,
RetInf,交易返回信息数组,-1,,
SrcSysSeqNo,源发起系统流水号,0,,
SrcSysId,源发起系统Id,0,,
SYS_HEAD,系统头部,-1,,
APP_HEAD,app头部,1,,
BranchId,编号,0,,
TlrNo,代码,0,,
TlrPswd,密码,0,,
TlrLvl,标题,0,,
TlrTp,标题,0,,
BsnSeqNo,编号,0,,
APP_HEAD,app头部,-1,,
BODY,交易码,1,,
CstIdTp,客户标识类型,0,CstIdTpYiHui,默认值CstIdT
CstId,客户标识,0,CstIdYiHui,默认值CstId
LoctStr,定位串,0,LoctStrYiHui,默认值LoctStr
QryLnNum,查询行数,0,QryLnNumYiHui,默认值QryLnNum
BODY,交易码,-1,,
services,这个是交易号,-1,,
','services,这个是交易号,1,,
SYS_HEAD,系统头部,1,,
SvcCd,服务代码,0,,
SvcScn,服务场景,0,,
CnsmSysId,调用方系统Id,0,,
CnsmSysSeqNo,调用方系统流水号,0,,
TranRetSt,交易返回状态,0,,
RetInf,交易返回信息数组,1,,
RetCd,返回码,0,,
RetMsg,交易返回信息,0,,
RetInf,交易返回信息数组,-1,,
SrcSysSeqNo,交易返源发起系统流水号回信息,0,,
SrcSysId,源发起系统Id,0,,
SYS_HEAD,系统头部,-1,,
APP_HEAD,app头部,1,,
APP_HEAD,app头部,-1,,
BODY,body部分,1,,
VerNo,版本号,0,VerNoYiHui,默认值VerNo
VrfyNo,未知编号,0,VrfyNoYiHuiHui,默认值VrfyNo
TranCd,前置交易码,0,TranCdYiHui,默认值VrfyNo
RqsTm,未知编号,0,RqsTmYiHui,RqsTm默认值
TotRcrdNum,总记录数,0,TotRcrdNumYiHui,默认值
TotPgNo,总页数,0,TotPgNoYiHui,默认值
PgRcrdNo,每页记录数,0,PgRcrdNoYiHui,默认值PgRcrdNoYiHui
GdsMssgArray,商品信息数组,1,GdsMssgArrayYiHui,默认值
CmdtyCd,商品编号,0,CmdtyCdYiHuiYiHui,默认值
CmdtyNm,商品名称,0,CmdtyNmYiHuiYiHui,默认值
CmdtyDsc,商品描述,0,CmdtyDscYiHui,默认值
CmdtyPntsPrc,商品描述,0,CmdtyPntsPrcYiHui,默认值CmdtyPntsPrc
CmdtyCashPrc,商品所需现金,0,CmdtyCashPrcYiHui,默认值CmdtyCashPrc
GdsTm,商品描述,0,GdsTmYiHui,默认值GdsTm
CmdtyLvlScr,商品评分,0,CmdtyLvlScrYiHui,默认值CmdtyLvlScrYiHui
PhotoNo,商品评分,0,PhotoNoYiHui,默认值PhotoNoYiHui
CnsmRuleID,商品评分,0,CnsmRuleIDYiHui,默认值CnsmRuleIDYiHui
CnsmRuleDsc,商品评分,0,CnsmRuleDscYiHui,默认值CnsmRuleDsc
GdsMssgArray,商品信息数组,-1,GdsMssgArrayYiHui,默认值GdsMssgArray
BODY,body结束,-1,GdsMssgArrayYiHui,默认值BODY
services,这个是交易号,1,,
');





